# Generated by Django 3.2.4 on 2022-01-28 07:36

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(default=None, max_length=60, unique=True, verbose_name='email')),
                ('status', models.CharField(default='INACTIVE', max_length=10, verbose_name='status')),
                ('date_joined', datetimeutc.fields.DateTimeUTCField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', datetimeutc.fields.DateTimeUTCField(auto_now_add=True, verbose_name='last_login')),
                ('modified', datetimeutc.fields.DateTimeUTCField(auto_now_add=True, verbose_name='modified')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
